### ISSUE TITLE
Change Currency to € (Euro) and why IMAP?

### ISSUE THREAD

**Issue by delta0815** [Receipt-Wrangler/receipt-wrangler-desktop#285]
What an amazing app!

I was just trying out the whole eco-system (Web-Version with self-hosted Unraid-image and also the Android app). While I have to agree that some of the features where a bit tricky, I guess I finally was able to get everything working.

There are currently two open items that I am struggeling with:

1. Is there any place where I can set the currency to €? I might have not seen it, but when I scan a receipt with the app, it automatically identifies this as $-amounts. While I MIGHT need dollar as well in the future, my default should always be €.
2. I had a hard time getting the email-part to work. But that was mainly due to the fact that I was trying to add the SMTP settings as my assumption was, that Receipt-Wrangler wants to send mails (e.g. for password-resets etc.) now that I saw your comment regarding a missing IMAP-log file I was able to get the settings up and running, however I'm a bit lost about the need for IMAP. I mean what's the purpose of Receipt Wrangler being able to receive mails. And is a sent-function not needed?

Thanks again for your great app. It really looks very promising!

Best regards,

Oliver

**Comment by Noah231515** [comment]
Hey Oliver,

Thanks for checking out Receipt Wrangler. I'd love to hear more about some of the trickiness that you had during configuration if you don't mind.

1. There isn't a place to do that at the moment. I have thought through 2 options, one option for simply a display for currencies as a global setting. This is easy enough to implement, but it is not that flexible since a receipt, or a group may be in a different currency. This brings me to currency conversion. This is the ideal solution; to fully support different currencies per receipt, per group and as a global default. That way the symbols mean something. This is really what I would like to do, but getting the current exchange rate typically costs money. Still something I'm investigating.
2. Currently Receipt Wrangler supports the ability to read receipts from a configured email with an attached image. Multiple images can be sent in one email, lets say 10 images for example. Then as the email is polled, the those 10 images will converted into receipts for the configured groups. Check out the documentation for more information: https://receiptwrangler.io/docs/concepts/email

Cheers
Noah

**Comment by delta0815** [comment]
Thanks for the detailed reply.

Regarding the trickiness: I’m not a Unraid/linux expert so I had to trial and error some of the settings. For example, I had no idea if there is any guidelines for ENCRYPTION_KEY and SECRET_KEY variables so I just gave it a try. Most of the Unraid apps have some specific explanation included. Or the Android app refused the scanning, so I had to dig into the AI part which I actually didn’t even intend to do. But quite frankly I guess this is all just because you allow everyone to have a very early access to your development which is great! 😊


  1.  Yeah, a conversion feature would be cool but I guess this can get pretty complex if you want to have a robust implementation. For a start a simple “Settings” page would be amazing. I would just like to be able to set some localization settings like local currency, local number-formatting, date-format etc. While I do understand that it looks a bit like double-work if you start with this and later implement a full currency-conversion system, I will have a hard time using an application that always shows the wrong currency 😉
  2.  Understood and it sounds great! 😊

Thanks again for the app and your support! If I can be of any help regarding the local-settings-request (or other topics) let me know.

Cheers,

Oliver



Von: Noah231515 ***@***.***>
Datum: Mittwoch, 3. Juli 2024 um 16:40
An: Receipt-Wrangler/receipt-wrangler-desktop ***@***.***>
Cc: oliver stein ***@***.***>, Author ***@***.***>
Betreff: Re: [Receipt-Wrangler/receipt-wrangler-desktop] Change Currency to € (Euro) and why IMAP? (Issue #285)

Hey Oliver,

Thanks for checking out Receipt Wrangler. I'd love to hear more about some of the trickiness that you had during configuration if you don't mind.

  1.  There isn't a place to do that at the moment. I have thought through 2 options, one option for simply a display for currencies as a global setting. This is easy enough to implement, but it is not that flexible since a receipt, or a group may be in a different currency. This brings me to currency conversion. This is the ideal solution; to fully support different currencies per receipt, per group and as a global default. That way the symbols mean something. This is really what I would like to do, but getting the current exchange rate typically costs money. Still something I'm investigating.
  2.  Currently Receipt Wrangler supports the ability to read receipts from a configured email with an attached image. Multiple images can be sent in one email, lets say 10 images for example. Then as the email is polled, the those 10 images will converted into receipts for the configured groups. Check out the documentation for more information: https://receiptwrangler.io/docs/concepts/email

Cheers
Noah

**Comment by Noah231515** [comment]
Appreciate the feedback! I updated the docs regarding those environment variables to provide a bit more guidance. I will update the unraid descriptions as well. As far as the mobile issue, that option won't exist if ai hasn't been set up yet, but that isn't in the latest version quite yet.

1. Excellent point. I will add some backlog items to support currency formats, and date formats. For now, I did add a Currency Display setting that will allow you to change from "$" to anything of your choice, update to the latest version to check it out. https://receiptwrangler.io/docs/concepts/system-settings/system-settings#currency-display

Please let me know if there's anything I can help you with!

Cheers,
Noah

**Comment by Noah231515** [comment]
Hey Oliver,

1. I'm not too familiar with unraid, but I'll take a deeper look to see if it is possible to add conditional fields, which would make this a bit cleaner to set up in unraid. I am also missing unraid documentation all together, so that would help at least.
2. It sounds like the Receipt Processing Settings may have set up, the settings to use was not set which settings to actually use were not set, which is located in the system settings https://receiptwrangler.io/docs/concepts/system-settings/system-settings#receipt-processing-settings. After setting that, AI will be enabled.

Your feedback has been very helpful so far, thanks so much!

Cheers,
Noah

**Comment by delta0815** [comment]
Hey Noah,

sorry for not getting back to you any earlier. I've tested the feature and now it looks great!

Regarding the unRaid template. It's absolutley doable. So no need to focus on optimizing it. Anyone who wants to get it up and running on unRaid schould be able to get it done with your template! :-)

Cheers,

Oliver
